apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rstudio
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: >-
      https://github.com/opendatahub-io-contrib/workbench-images/tree/main/recipes/rstudio-r-c9s-py311_2023c_20230922
    opendatahub.io/notebook-image-name: >-
      RStudio
    opendatahub.io/notebook-image-desc: |-
      RStudio is an integrated development environment (IDE)
      for R, a programming language for statistical computing
      and graphics. It provides a user-friendly interface for
      data analysis, visualization, and reporting, making it a
      popular choice among data scientists and statisticians.
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 1.0.0
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/opendatahub-contrib/workbench-images:rstudio-r-c9s-py311_2023c_latest'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
